### ISSUE TITLE
Documentation should be more specific about actions taken

### ISSUE THREAD

**Issue by ggeldenhuis** [hercules-team/augeasproviders_grub#33] opened 2018-05-31 09:44 UTC
It is not 100% clear from the documentation whether the provider also actually runds grub2-mkconfig after setting/changing settings. It could be argued that it is obvious but for the sake of clarity it would be useful if the documentation could specifically say that grub2-mkconfig is run after setting a value. I looked through the code and that is indeed what happens. I am happy to do a tiny PR for the doc update if there is agreement.

**Comment by kenyon** [comment] 2020-11-25 06:20
Looks like a duplicate of #40.

**Comment by raphink** [comment] 2021-01-18 14:15
Thanks @kenyon

**Closed by raphink** 2021-01-18 14:15 UTC
